### ISSUE TITLE
Modificar centroide del mapa

### ISSUE THREAD

**Issue by humano** [AddressForAll/WS-CO#13]
modificar las coordenadas iniciales del mapa a const mapCenter = [-74.863987, 5.179751];
 addressforall.js line 5  tambien un nivel de zoom que permita ver bogota y medellin

**Comment by elpbatista** [comment]
Eso no consigue el resultado esperado porque el centroid entre Bogotá y Medellín es en un lugar intermedio del que no tenemos datos así que la idea de seleccionar las ciudades sigue siendo la mejor

**Comment by elpbatista** [comment]
medio resuelto con lo de switch de ciudad desde la URL... a ver si aparece la solución

**Comment by ppKrauss** [comment]
> medio resuelto con lo de switch de ciudad desde la URL... a ver si aparece la solución

Solução aceita e implementada conforme "seletor de cidade", issue #9 

PS: implementado em https://local.addressforall.org/CO/map
