### ISSUE TITLE
Incluir links en la página del mapa

### ISSUE THREAD

**Issue by humano** [AddressForAll/WS-CO#4]
incluir en la página de del mapa los links al repositorio de GitHUB y documentación de la API

**Comment by ppKrauss** [comment]
* "incluir en la página de del mapa" = http://local.addressforall.org/
* "link al repositorio de GitHUB" = https://git.AddressForAll.org/WS-CO
* "link al documentación de la API" = https://git.AddressForAll.org/WS-CO/tree/main/doc#readme

**Comment by Gamamarcello** [comment]
Links adicionados

**Comment by ppKrauss** [comment]
Adicionados na nova versão

* mapa em https://local.addressforall.org/map/
* link mapa em  https://local.addressforall.org/
* dados em https://local.addressforall.org/dados
* api em https://local.addressforall.org/api
* evento em https://local.addressforall.org/evento
