### ISSUE TITLE
Trazer pasta de fonte da fonte para deploy

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS-CO#5]
Trazer para cá a pasta uma cópia da pasta `/fontend`,
https://github.com/elpbatista/address-for-all/tree/main/frontend
com ela podemos fazer o *deploy* gerador da pasta `/web`.

Avisar aqui se correu tudo bem e melhorar o README se necessário.

**Comment by Gamamarcello** [comment]
´Tudo certo com a migração da pasta Peter

Realizei correções no responsivo do frontend

**Comment by ppKrauss** [comment]
Parece que faltou deixar registrado no git o passo-a-passo:

1. Copia o original do Batista;
2. Copia as suas modificações.

sem isso nem eu nem o Batista poderemos usar a ferramnenta DIFF do git para saber o que você fez. Vou reverter e começa denovo.  É preciso que todos usem o git corretamente.
