### ISSUE TITLE
Reconociminto de fuentes

### ISSUE THREAD

**Issue by humano** [AddressForAll/WS-CO#7]
poner el el mapa un link de reconocimiento a fuentes que conduzca hasta un micrositio donde esté el listyado de fuentes de datos de4 Colombia

**Comment by ppKrauss** [comment]
Perguntas para @humano : 
* podemos fazer merge desta *issue*  com a [*issue* 4](https://github.com/AddressForAll/WS-CO/issues/4)?
* "micrositio donde esté el listyado de fuentes de datos de  Colombia", é https://git.digital-guard.org/preserv-CO correto?

PS: podemos adaptar no site algo similar ao que fizemos em [digital-guard/preserv/docs/pt/list-primaryData-byHash.md](https://github.com/digital-guard/preserv/blob/main/docs/pt/list-primaryData-byHash.md)

**Comment by ppKrauss** [comment]
Resolvido com https://local.addressforall.org/dados
