### ISSUE TITLE
Depuración de los datos de 2 ciudades

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS-CO#8]
En  20/12/2021  Fredy Rivera:
> (...) le he dado instrucciones a @elpBatista  para que se concentre en la depuración de los datos, pues veo con lo que dicen sobre las carreras que tenemos problemas con los que no contabamos, el está comprometido a pasar el CSV de los datos depuardos hoy (...)

**Comment by elpbatista** [comment]
ya está
