### ISSUE TITLE
Seletor de cidade

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/WS-CO#9]
a caixa de busca requer ao  lado um HTML-SELECT de nomes de cidade. Toda busca será restrita a uma cidade... Por hora serão apenas 2 ou 3 cidades.

------

Discussão original:

> (Peter) A interface vai ter um Select para cidade, não faz sentido fazer busca de endereço no país inteiro, o usuário sabe a cidade

> (Fredy) De acuerdo, entonces hay que prever que  la caja de búsqueda tenga un selector de ciudad y de igual forma en la API, en este caso es un combo select de 
Departamento-ciudad, pero esto lo debemos hacer cuando los datos estén correctamente importados

**Comment by ppKrauss** [comment]
Para **futuro** algo mais complexo, conforme @elpbatista :

>  Se puede hacer igual que el Website de AirBnB que primero ofrece una caja de selección antes de enviar al usuario al mapa. También AirBnB tiene bases de datos partidas por ciudades/regiones así todo el tiempo se está manejando con un subconjunto de los datos

> Eso resolveria que se puedan hacer llamadas al API desde cualquier plataforma/servicio de nube/proveedor. Muchos proveedores entienden las llamadas mixtas (http+https) en el mismo website como una amenaza de seguridad y bloquean las HTTP.

**Comment by ppKrauss** [comment]
@elpbatista  por favor indicar como o SELECT envia parametro de cidade selecionada

**Comment by humano** [comment]
Por ahora un selector en trte Medellin y Bogotá funciona para la demostracion de mañana.

**Comment by ppKrauss** [comment]
@elpbatista  me mostre aqui a função SQL que usa e onde está o parâmetro "cidade" na função SQL.
Por exemplo `api.lookup(text)` não tem ID da cidade como parâmetro. Criar uma função onde `Medellin` ou `Bogotá` ou true ou false para is_medellin, permita a interface solicitar a API buscar (*search*) numa cidade especificada

**Comment by elpbatista** [comment]
Una solución "chapucera" pero soluciona un problema en lo que llega la solución definitiva:
https://addressforall.netlify.app/?bogota
https://addressforall.netlify.app/?medellin

**Comment by ppKrauss** [comment]
> Una solución "chapucera" pero soluciona un problema en lo que llega la solución definitiva: https://addressforall.netlify.app/?bogota https://addressforall.netlify.app/?medellin

Ok, resolvido o seletor com essa forma de identificação para fazer `onChange="window.location.replace(this.value)"`, ver:

* `<select name="sel_city"` em https://github.com/AddressForAll/WS-CO/blame/main/frontend/index.html#L27
* e selected option em https://github.com/AddressForAll/WS-CO/blame/main/frontend/index.html#L46
